config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :todo_lists
  end
  root 'todo_lists#index'

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true, length: {in: 2..255}

  def self.complete
    where("completed_at is not null")
  end

  def self.incomplete
    where(completed_at: nil)
  end

  def completed?
    !completed_at.blank?
  end

  def toggle_completion!
    if completed?
      update_attribute(:completed_at, nil)
    else
      update_attribute(:completed_at, Time.now)
    end
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
  validates :title, presence: true, length: { in: 1..60 }
  validates :description, length: { in: 0..120 }
  scope :has_description, -> { where.not("description" => nil)}
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    skip_before_filter :verify_authenticity_token
    protect_from_forgery with: :null_session
    before_filter :authenticate

    def authenticate
      authenticate_or_request_with_http_basic do |user, password|
        user == "phil" && password == "catspaw"
      end
    end
  end
end

app/controllers/api/todo_lists_controller.rb
class Api::TodoListsController < Api::ApiController
  def index
    render json: TodoList.all
  end

  def show
    render json: TodoList.find(params[:id])
  end

  def create
    list = TodoList.new(list_params)
    if list.save
      render status: 200, json: {
        message: "Successfully created To-do List",
        todo_list: list
      }.to_json
    else
      render status: 422, json: {
        message: list.errors
      }.to_json
    end
  end

  def update
    list = TodoList.find(params[:id])
    if list.update(list_params)
      render status: 200, json: {
        message: "Successfully Updated Todo List with ID: #{params[:id]}",
        todo_list: list
      }
    else
      render status: 422, json: {
        message: list.errors
      }.to_json
    end
  end

  def destroy
    list = TodoList.find(params[:id])
    list.destroy
    render status: 200, json: {
      message: "Successfully deleted Todo List with id of #{params[:id]}"
    }
  end

  private
  def list_params
    params.require("todo_list").permit("title")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list
  def index
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      redirect_to @todo_list
    else

    end
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.toggle_completion!
    redirect_to @todo_list, notice: "Todo item updated."
  end

  private
  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @todo_lists = TodoList.all
  end
  def show
    @todo_list = TodoList.find(params[:id])
  end
  def new
    @todo_list = TodoList.new
  end
  def edit
    @todo_list = TodoList.find(params[:id])
  end
  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save
      redirect_to @todo_list
    else
      render '/todo_lists/new'
    end
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if request.path == '/todo_lists' %>
    <div class="header">
      <span>Best Todo Maker Ever</span>
    </div>
  <% else %>
    <div class="header">
      <a href="/todo_lists">Back Home</a>
    </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/todo_items/index.html.erb
<% @todo_list.todo_items.each do |item| %>
  <li>
    <%= item.content %>
  </li>
<% end %>

app/views/todo_lists/index.html.erb
<h1>Current Todo Lists</h1>
<%= link_to "Create New List", new_todo_list_path %>
<% @todo_lists.each do |list| %>
  <h4><%= link_to list.title, list %></h4>
<% end %>

app/views/todo_lists/new.html.erb
<%= form_for @todo_list do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this @todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/todo_lists/show.html.erb
<!-- <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %> -->

<%= @todo_list.title %>
<%= @todo_list.description %>

<%= form_for [@todo_list, TodoItem.new] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>
<h4>Completed Items</h4>
<ul>
<% @todo_list.todo_items.complete.each do |list_item| %>
  <li>
    <span class="list_item"><%= list_item.content %></span><%= link_to "Mark Incomplete", complete_todo_list_todo_item_path(@todo_list, list_item), method: :patch %>
  </li>
<% end %>
</ul>
<h4>Incomplete Items</h4>
<ul>
<% @todo_list.todo_items.incomplete.each do |list_item| %>
  <li>
    <span class="list_item"><%= list_item.content %></span><%= link_to "Mark Complete", complete_todo_list_todo_item_path(@todo_list, list_item), method: :patch %>
  </li>
<% end %>

</ul>